name: Build LaTeX document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex

    - name: Commit and push generated PDF
      env:
        ACTIONS_PATH: ${{ secrets.ACTIONS_PATH }}
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        mv main.pdf CV.pdf
        git add CV.pdf
        git commit -m 'Add generated CV.pdf'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PATH }}@github.com/${{ github.repository }}
        git push origin main
