name: Build LaTeX document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@v2

    - name: Compile LaTeX document
      run: latexmk -pdf -interaction=nonstopmode -file-line-error main.tex

    - name: Commit and push generated PDF
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add main.pdf
        git commit -m 'Add generated PDF'
        git push
